### ISSUE TITLE
Missing W3C in IoT Wikipedia page

### ISSUE THREAD

**Issue by relu91** [w3c/wot-marketing#94] opened 2020-11-24 09:46 UTC
If you have a look at the Wikipedia Internet of Things page, there is a section about [Standards and standards organizations](https://en.wikipedia.org/wiki/Internet_of_things#Standards_and_standards_organizations). Although Web of Things is mentioned here and there, there is no mention of W3C standardization work in that section.

**Comment by Citrullin** [comment] 2020-12-03 13:07
Generally speaking the [Web of Things Wikipedia page](https://en.wikipedia.org/wiki/Web_of_Things) also needs a lot of work. I edited it a while ago, since the version back then was outdated and was referring to Web of Things as a standard on top of HTTP only etc. 
So, when someone has a bit free time, it would be great, if we start creating a more useful and informative Wikipedia page.

**Comment by sebastiankb** [comment] 2020-12-03 13:51
+1 

It would be very helpful when we can publish the wiki entry for Thing Description. There is a draft available by @egekorkan however, it was rejected twice due to the lack of independent references. 

https://en.wikipedia.org/wiki/Draft:Thing_Description

**Comment by Citrullin** [comment] 2020-12-03 14:20
> +1
> 
> It would be very helpful when we can publish the wiki entry for Thing Description. There is a draft available by @egekorkan however, it was rejected twice due to the lack of independent references.
> 
> https://en.wikipedia.org/wiki/Draft:Thing_Description

Okay, Wikipedia is an interesting world by itself. Thanks for mentioning this. I try to fix that and fit into their requirements. In case there aren't enough sources, we just need to create some. ^^

**Comment by egekorkan** [comment] 2020-12-03 15:09
I actually had sources but it still didn't work. Maybe the way they were formatted was not good. In any case, I would want to know what I need to do. I have even submitted it in their Q&A forum/chat but nobody replied.

**Comment by Citrullin** [comment] 2020-12-03 17:03
> I actually had sources but it still didn't work. Maybe the way they were formatted was not good. In any case, I would want to know what I need to do. I have even submitted it in their Q&A forum/chat but nobody replied.

The best way to reach out to them is on the physical meetings. But Corona... ^^ 
I changed the article and added some other sources. Let's see, if they are going to approve it. There are not that many sources available though. The once who are, are outdated and are referring to this HTTP proposal by Dominique. 
But I guess this is nothing new to you. These sources are needed for Wikipedia articles. I will create a short list of some reliable source. It might be a good idea to reach out to some of them in order to get some articles published. This is also a good idea besides having reliable sources for Wikipedia. I will eventually create a PR for this with more details.

**Comment by Citrullin** [comment] 2020-12-03 21:07
Okay, as I guessed. Even with removing big chunks of the article, it got rejected. So, there needs to be more media coverage before it gets approved.

**Comment by egekorkan** [comment] 2020-12-03 21:29
Thank you for the effort. What I don't get is that there are lots of articles with less references. Maybe the sources we have are not credible enough?

**Comment by Citrullin** [comment] 2020-12-03 21:42
> Thank you for the effort. What I don't get is that there are lots of articles with less references. Maybe the sources we have are not credible enough?

Yep, that's the main issue. Even though the W3C should be a very credible source. Wikipedia is a weird ecosystem by itself. (From my perspective.) The articles get reviewed by people who have no idea about the topic itself. There is also not much you can do, as a normal user, against the decisions of the admins. You can try to go to a meeting and discuss this topic with other admins. You can, of course, also escalate the topic and get other admins to decide on it. But it got rejected 3 times. I don't see a big chance to get this through. There is also a big difference between the Wikipedia for each region. 
From my own experience: I had no issue to get [this section](https://de.wikipedia.org/wiki/IOTA_(Kommunikationsprotokoll)#Jinn_Labs_und_Spenden_in_H%C3%B6he_von_65_Tera_IOTA) into the German Wikipedia. The source was seem as credible enough. While on the English Wikipedia this ended up in a [huge discussion](https://en.wikipedia.org/wiki/User_talk:David_Gerard#IOTA:_65_Ti_Fight) and at some point the admin even just ignored my arguments.  

From a strategic point of view: We need more articles about this topic anyways. Get some credible sources and try to get this article into the English Wikipedia again.

**Comment by egekorkan** [comment] 2020-12-03 21:45
Interesting insight into this "new" world, thank you! :D

**Comment by Citrullin** [comment] 2020-12-03 21:46
> 
> 
> Interesting insight into this "new" world, thank you! :D

And it all started with such an[ innocent contribution](https://de.wikipedia.org/wiki/Spezial:Beitr%C3%A4ge/Citrullin): "12:08, 13. Jun. 2014 Unterschied Versionen −218‎ Nachrichten- und Presseagentur ‎ Link entfernt, der nicht sonderlich relevant für diesen Artikel ist. " :D 
No problem. I am here to help.

**Comment by relu91** [comment] 2020-12-04 08:20
By the way, sorry for the dead link in the issue description. I've updated it. I think that the discussion has gone a little bit off-topic. We should open a dedicated issue for the TD Wiki page so that we can keep track of the state there. The issue itself here is to just add an entry in [this table](https://en.wikipedia.org/wiki/Internet_of_things#Standards_and_standards_organizations). It might be nothing but as the page is main entry point about IoT, it might give us a little media coverage. Plus since it is a trivial addition I don't think it will be rejected.

**Comment by sebastiankb** [comment] 2020-12-07 07:40
@Citrullin thanks for your update

Could this be a strategy that we simply remove the entire entry except the first sentence "W3C WoT Thing Description (TD) is a W3C recommendation[1]."  
If this is approved (hopefully), we can build up this page step by step and we can see what the reviewers are actually complaining when one step is not good enough.

**Comment by sebastiankb** [comment] 2020-12-07 12:15
I just realized that the references are indeed not perfect. There is no official reference to the W3C TD spec yet. Reference [1] points to a chair of a university. I can fix this.

**Comment by egekorkan** [comment] 2020-12-07 12:52
Interesting, my original version had all those: https://en.wikipedia.org/w/index.php?title=Draft:Thing_Description&oldid=951529387

So it is not the root of the problem why they reject it.

I have also put a much simpler version in the beginning but that was also rejected. I think it actually needs more text in it and more references from trusted sources (trusted according to Wikipedia).

**Comment by Citrullin** [comment] 2020-12-07 13:28
> I just realized that the references are indeed not perfect. There is no official reference to the W3C TD spec yet. Reference [1] points to a chair of a university. I can fix this.

"Wikipedia requires independent sources, we have very little interest in what their own website says." - Theroadislong
That is why I changed it. The whole example section doesn't have any independent reliable sources. They don't count the W3C as reliable independent source, since the standard is by the W3C. I kind of get their point. So, what they want to see are articles, paper etc. by other, independent, parties, not the W3C. The sources also have to show that this standard has a relevance to the Wikipedia. If it doesn't have enough relevance, it eventually gets deleted either way. 

> I have also put a much simpler version in the beginning but that was also rejected. I think it actually needs more text in it and more references from trusted sources (trusted according to Wikipedia).

I agree on that. Problem is just, there aren't enough. 

From a strategic point of view it makes sense to start reaching out to some magazines, blogs etc. and write some articles about the standard. This is generally also a good idea to reach more people. I collected a bunch of reliable sources one could write articles for. Just a lot of work and I don't know, if any of you has enough time to drive this forward. 
I will eventually create a short PR with these sites etc. and strategy idea for it.

**Comment by relu91** [comment] 2020-12-20 16:49
> From a strategic point of view it makes sense to start reaching out to some magazines, blogs etc. and write some articles about the standard. This is generally also a good idea to reach more people. I collected a bunch of reliable sources one could write articles for. Just a lot of work and I don't know, if any of you has enough time to drive this forward.
I will eventually create a short PR with these sites etc. and strategy idea for it.

I agree, if we take as inspiration the Reference section of  [Connected Home over IP](https://en.wikipedia.org/wiki/Connected_Home_over_IP), you can see that they are just a bunch of articles from the most known magazines.

**Comment by sebastiankb** [comment] 2020-12-23 08:41
Hi all, I spend some time to work on  https://en.wikipedia.org/wiki/Draft:Thing_Description

I integrate several different references. Sometimes I'm not sure which is to be higher ranked: the reference to one's own Wikipedia entry or to outside (original) sources. I have made a mixture.  

I will resubmit today. Lets see what happen...

**Comment by egekorkan** [comment] 2021-05-31 19:41
The actual root of the issue is not resolved by the way :)

**Comment by egekorkan** [comment] 2021-11-30 12:46
I will add a new line at the end, in order of columns:
1. W3C  (Short Name)
2. World Wide Web Consortium (Long Name)
3. Listing Normative and Informative Spec of the WG/IG and TD Wikipedia Page (Standards under development)
4. Our homepage (Other Notes)

**Comment by egekorkan** [comment] 2021-11-30 16:08
Available at https://en.wikipedia.org/wiki/Internet_of_things#Standards_and_standards_organizations

**Comment by danielpeintner** [comment] 2021-12-01 09:11
Note: for discovery I would link to
https://www.w3.org/TR/wot-discovery/
instead of
https://w3c.github.io/wot-discovery/

**Comment by egekorkan** [comment] 2021-12-05 21:48
Done @danielpeintner :)

**Comment by egekorkan** [comment] 2021-12-14 12:17
Given that it is now implemented, the issue can be closed. (call of 14.12.2021)

**Closed by egekorkan** 2021-12-14 12:17 UTC
Labels: Propose closing
